export const siteConfig = {
  name: "DNA WATCHES Magasin de bijoux et de montres",
  tagline: "Elegance intemporelle. Precision exceptionnelle.",
  baseUrl: "https://www.oussaura.com",
  phone: "+213778997572",
  phone2: "+213778997572",
  phone3: "+213778997572",
  email: "dnawatches.business@gmail.com",
  address: "Alger, Algerie",
  googleMapsLink: "https://maps.app.goo.gl/nh5JsSvQrQiXgHSj7",
  whatsappLink: "https://wa.me/213797537731",
  instagramLink: "https://www.instagram.com/dna__watches/",
  facebookLink: "https://www.facebook.com/dz.vente.tt",
  tiktokLink: "https://www.tiktok.com/@oussaura.boutique",
  description:
    "DNA WATCHES Magasin de bijoux et de montres propose des montres originales, bijoux et accessoires premium avec livraison dans les 58 wilayas et paiement à la livraison.",
  keywords: [
    "DNA WATCHES",
    "montres Algerie",
    "bijoux Algerie",
    "montres originales",
    "magasin de montres",
    "livraison 58 wilayas",
  ],
};
